name: Continuous Integration Build

on:
  pull_request:
      branches:
        - main
        - quarkus-2.13
  push:
      branches:
        - main
        - quarkus-2.13
      paths-ignore:
        - '.build/**'

jobs:

  build-images:
    name: Build images for ${{ matrix.configuration }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - .github/native-images.yaml
          - .github/mandrel-images.yaml
          - .github/s2i-native-images.yaml
          - .github/tooling-images.yaml
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build images
      run: jbang/bin/jbang .github/build-images.java ${{ matrix.configuration }}

  binary-s2i:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (binary) images
      run: .github/build-s2i-binary-images.sh        

  distroless:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build Distroless images
      run: .github/build-distroless-images.sh

  micro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build Micro images
      run: .github/build-micro-images.sh
