name: Push Images to Quay
on:
  deployment:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-images:
    name: Build and push images for ${{ matrix.configuration }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - .github/native-images.yaml
          - .github/mandrel-images.yaml
          - .github/s2i-native-images.yaml
          - .github/tooling-images.yaml
    steps:
    - uses: actions/checkout@v1
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build images
      run: jbang/bin/jbang .github/build-images.java ${{ matrix.configuration }}
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh                            

  binary-s2i-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (binary) images
      run: .github/build-s2i-binary-images.sh        
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh                                

  distroless-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Prerequisites
      run: .github/ci-prerequisites.sh
    - name: Build S2I (binary) images
      run: .github/build-distroless-images.sh        
    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: .github/push-images.sh          

  # micro-build-and-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1    
  #   - name: Prerequisites
  #     run: .github/ci-prerequisites.sh
  #   - name: Build S2I (binary) images
  #     run: .github/build-micro-images.sh        
  #   - name: Push images
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       QUAY_USER: ${{ secrets.QUAY_USER }}
  #       QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
  #     run: .github/push-images.sh          
